set PYTHONPATH=%PYTHONPATH%;../;./crawler/;./logic/;
start python crawler\crawl_master.py
ping localhost -n 1
start python crawler\proxy_mgr.py 1
ping localhost -n 1
start python crawler\proxy_mgr.py 2
ping localhost -n 1
start python crawler\proxy_mgr.py 3
ping localhost -n 1
start python crawler\proxy_mgr.py 4
ping localhost -n 1
start python crawler\crawl_slave.py log\slave1
ping localhost -n 1
start python crawler\crawl_slave.py log\slave2
ping localhost -n 1
start python crawler\crawl_slave.py log\slave3
ping localhost -n 1
start python crawler\crawl_slave.py log\slave4
ping localhost -n 1
start python crawler\crawl_slave.py log\slave5
ping localhost -n 1
start python crawler\crawl_slave.py log\slave6
ping localhost -n 1
start python crawler\crawl_slave.py log\slave7
ping localhost -n 1
start python crawler\crawl_slave.py log\slave8
ping localhost -n 1
start python crawler\crawl_slave.py log\slave9
ping localhost -n 1
start python crawler\crawl_slave.py log\slave10
ping localhost -n 1
start python crawler\crawl_slave.py log\slave1
ping localhost -n 1
start python crawler\crawl_slave.py log\slave12
ping localhost -n 1
start python crawler\crawl_slave.py log\slave13
ping localhost -n 1
start python crawler\crawl_slave.py log\slave14
ping localhost -n 1
start python crawler\crawl_slave.py log\slave15
ping localhost -n 1
start python crawler\crawl_slave.py log\slave16
ping localhost -n 1
start python crawler\crawl_slave.py log\slave17
ping localhost -n 1
start python crawler\crawl_slave.py log\slave18
ping localhost -n 1
start python crawler\crawl_slave.py log\slave19
ping localhost -n 1
start python crawler\crawl_slave.py log\slave20
ping localhost -n 1
start python crawler\crawl_slave.py log\slave21
ping localhost -n 1
start python crawler\crawl_slave.py log\slave22
ping localhost -n 1
start python crawler\crawl_slave.py log\slave23
ping localhost -n 1
start python crawler\crawl_slave.py log\slave24
ping localhost -n 1
start python crawler\crawl_slave.py log\slave25
ping localhost -n 1
start python crawler\crawl_slave.py log\slave26
ping localhost -n 1
start python crawler\crawl_slave.py log\slave27
ping localhost -n 1
start python crawler\crawl_slave.py log\slave28
ping localhost -n 1
start python crawler\crawl_slave.py log\slave29
ping localhost -n 1
start python crawler\crawl_slave.py log\slave30


